---
site_name: "{{ cookiecutter.project_name }}"
site_description: "{{ cookiecutter.project_description }}"
site_url: "https://{{ cookiecutter.github_username }}.github.io/{{ cookiecutter.__project_slug }}"
theme:
  name: "material"
