---
exclude: "{{cookiecutter.__project_slug}}"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    -   id: shellcheck

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        args: [--fix]

  # requires a separate install step
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      # check here if you need a reference for errors
      # https://cbea.ms/git-commit/#separate
      # https://jorisroovers.com/gitlint/latest/rules/builtin_rules/
      - id: gitlint

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.5.0"
    hooks:
      - id: pyproject-fmt
